name: check-player

on: [pull_request, workflow_dispatch]

jobs:
  check-player:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'

      - name: Get domline tool
        run: git clone https://github.com/2kodevs/domline.git

      - name: Run ls
        run: ls

      - name: Run check script
        run: domline/build/domline check --path players --config domline/config.yaml
