name: check-player

on: [pull_request, workflow_dispatch]

jobs:
  check-player:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get domline tool
        run: ls && git clone https://github.com/2kodevs/domline.git && cd domline && make compile

      - name: Run ls
        run: ls

      - name: Run check script
        run: domline/build/domline check --path players
